import { Link } from 'react-router-dom';
import { ShieldCheck, Cpu, BarChart, ArrowUpRight, Zap, RefreshCw, Lock, Sparkles } from 'lucide-react';

export default function InstitutionalTradingSection() {
  return (
    <>
      <section id="trading-ecosystem" className="py-20 bg-dark-950 relative overflow-hidden border-y border-dark-600/80">
        {/* Glow effects in background */}
        <div className="absolute top-1/4 left-10 w-96 h-96 bg-gold-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute bottom-10 right-10 w-96 h-96 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none" />

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="grid gap-12 items-center">
            {/* Centered Content Column */}
            <div className="space-y-6 text-center mx-auto max-w-3xl">
              <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full border border-gold-500/30 bg-gold-500/10 text-gold-400 text-xs font-bold uppercase tracking-wider">
                <Sparkles size={14} /> Institutional-Grade Infrastructure
              </div>

              <h2 className="text-3xl sm:text-4xl lg:text-5xl font-black text-white leading-tight">
                Algorithmic Trading & <span className="gradient-text">Liquidity Intelligence</span>
              </h2>

              <p className="text-gray-300 text-base leading-relaxed">
                Every dollar committed to the Solvex Trading Pool is deployed across institutional cross-exchange arbitrage, automated liquidity provisioning, and systematic quantitative algorithms — producing stable, predictable daily yield.
              </p>

              {/* Feature Cards */}
              <div className="space-y-4 pt-2 text-left">
                <div className="p-4 rounded-2xl bg-dark-900/80 border border-dark-600/80 hover:border-gold-500/30 transition-all flex items-start gap-4">
                  <div className="p-2.5 rounded-xl bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 shrink-0 mt-0.5">
                    <ShieldCheck size={20} />
                  </div>
                  <div>
                    <h4 className="text-white font-bold text-sm mb-1">Automated Stop-Loss & Capital Preservation</h4>
                    <p className="text-gray-400 text-xs leading-relaxed">
                      Strict max-drawdown rules ensure pool principal is shielded against extreme market volatility.
                    </p>
                  </div>
                </div>

                <div className="p-4 rounded-2xl bg-dark-900/80 border border-dark-600/80 hover:border-gold-500/30 transition-all flex items-start gap-4">
                  <div className="p-2.5 rounded-xl bg-gold-500/10 text-gold-400 border border-gold-500/20 shrink-0 mt-0.5">
                    <Zap size={20} />
                  </div>
                  <div>
                    <h4 className="text-white font-bold text-sm mb-1">Multi-Asset Cross Hedging</h4>
                    <p className="text-gray-400 text-xs leading-relaxed">
                      Strategies span Spot Crypto, Perpetuals, Spot Gold (XAU/USD), and Global Macro FX pairs.
                    </p>
                  </div>
                </div>

                <div className="p-4 rounded-2xl bg-dark-900/80 border border-dark-600/80 hover:border-gold-500/30 transition-all flex items-start gap-4">
                  <div className="p-2.5 rounded-xl bg-blue-500/10 text-blue-400 border border-blue-500/20 shrink-0 mt-0.5">
                    <BarChart size={20} />
                  </div>
                  <div>
                    <h4 className="text-white font-bold text-sm mb-1">Automated Daily ROI Crediting</h4>
                    <p className="text-gray-400 text-xs leading-relaxed">
                      Yields generated by trading desks are automatically credited daily to your member wallet at midnight.
                    </p>
                  </div>
                </div>
              </div>

              <div className="pt-2 flex items-center justify-center gap-4">
                <Link
                  to="/register"
                  className="inline-flex items-center gap-2 px-6 py-3 rounded-xl font-bold bg-gradient-to-r from-gold-500 to-gold-400 text-dark-900 hover:brightness-110 transition-all text-sm gold-glow"
                >
                  Join Trading Pool <ArrowUpRight size={16} />
                </Link>
                <a
                  href="#live-markets"
                  className="inline-flex items-center gap-2 px-5 py-3 rounded-xl font-semibold border border-dark-600 text-gray-300 hover:text-gold-400 hover:border-gold-400 text-sm transition-all"
                >
                  View Live Market Feeds
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section id="how-we-earn" className="py-20 bg-dark-950 text-center">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-black text-white mb-6">
            How SolveX Generates Returns
          </h2>
          <p className="text-gray-300 text-base mb-10">
            SolveX operates as an institutional-style group trading pool, deploying pooled investor capital into the global Forex market through a professional trading desk. Our team of experienced traders executes structured, risk-managed strategies across major currency pairs, generating consistent trading profits that are distributed back to investors as scheduled returns.
          </p>
          <div className="grid md:grid-cols-3 gap-6">
            <div className="p-4 rounded-2xl bg-dark-900/80 border border-dark-600/80 hover:border-gold-500/30 transition-all">
              <h3 className="text-white font-bold text-lg mb-2">Group Forex Trading</h3>
              <p className="text-gray-400 text-sm">
                Investor funds are pooled together and actively traded in the Forex market by our professional trading team, leveraging institutional-grade strategies and risk management.
              </p>
            </div>
            <div className="p-4 rounded-2xl bg-dark-900/80 border border-dark-600/80 hover:border-gold-500/30 transition-all">
              <h3 className="text-white font-bold text-lg mb-2">Transparent Distribution</h3>
              <p className="text-gray-400 text-sm">
                Trading profits generated from Forex operations are distributed to investors according to their selected package and applicable ROI schedule.
              </p>
            </div>
            <div className="p-4 rounded-2xl bg-dark-900/80 border border-dark-600/80 hover:border-gold-500/30 transition-all">
              <h3 className="text-white font-bold text-lg mb-2">Risk-Managed Approach</h3>
              <p className="text-gray-400 text-sm">
                Our trading desk follows strict risk management protocols to protect pooled capital while aiming for consistent, sustainable returns across market cycles.
              </p>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
